### PR TITLE
Added Java/PrimeOrNot File

### PR DESCRIPTION
**Pull request by RiyaBhandari-2811**
Solved Issue no. #3

### CODE REVIEW

**Comment by RiyaBhandari-2811** [comment]
Is your repo not participating in hacktober fest???
Asking coz it is showing me that project is not participating.

**Comment by printf-twinkle** [comment]
@RiyaBhandari-2811  wait for some time, you will see the change on the website

**Comment by RiyaBhandari-2811** [comment]
Ok if I see any chances I'll let you know

**Comment by RiyaBhandari-2811** [comment]
Hey ! You're participating now wowiee 🥳🥳

**Pull request merged**
